apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: spring-game-score
build:
  artifacts:
  - image: luiscortes/spring-game-score
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: myDep
    namespace: mynamespace  #
    port: 8080 #
    localPort: 8080 # *Optional*
